// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	create: (newInstance: NewInstanceDto) => __TAURI_INVOKE<null>("plugin:instance|create", { newInstance }),
	import: (importInstance: ImportInstanceDto) => __TAURI_INVOKE<null>("plugin:instance|import", { importInstance }),
	listImporters: () => __TAURI_INVOKE<CapabilityEntryDto<ImporterCapabilityMetadataDto>[]>("plugin:instance|list_importers"),
	list: () => __TAURI_INVOKE<InstanceDto[]>("plugin:instance|list"),
	get: (id: string) => __TAURI_INVOKE<InstanceDto>("plugin:instance|get", { id }),
	getDir: (id: string) => __TAURI_INVOKE<string>("plugin:instance|get_dir", { id }),
	install: (id: string, force: boolean) => __TAURI_INVOKE<null>("plugin:instance|install", { id, force }),
	update: (id: string) => __TAURI_INVOKE<null>("plugin:instance|update", { id }),
	edit: (id: string, editInstance: EditInstanceDto) => __TAURI_INVOKE<InstanceDto>("plugin:instance|edit", { id, editInstance }),
	remove: (id: string) => __TAURI_INVOKE<null>("plugin:instance|remove", { id }),
	launch: (id: string) => __TAURI_INVOKE<MinecraftProcessMetadataDto>("plugin:instance|launch", { id }),
	stop: (uuid: string) => __TAURI_INVOKE<null>("plugin:instance|stop", { uuid }),
	importContents: (instanceId: string, contentType: ContentTypeDto, sourcePaths: string[]) => __TAURI_INVOKE<null>("plugin:instance|import_contents", { instanceId, contentType, sourcePaths }),
	listContent: (id: string) => __TAURI_INVOKE<{ [key in string]: ContentFileDto }>("plugin:instance|list_content", { id }),
	installContent: (payload: ContentInstallParamsDto) => __TAURI_INVOKE<null>("plugin:instance|install_content", { payload }),
	enableContents: (id: string, contentPaths: string[]) => __TAURI_INVOKE<null>("plugin:instance|enable_contents", { id, contentPaths }),
	disableContents: (id: string, contentPaths: string[]) => __TAURI_INVOKE<null>("plugin:instance|disable_contents", { id, contentPaths }),
	removeContents: (id: string, contentPaths: string[]) => __TAURI_INVOKE<null>("plugin:instance|remove_contents", { id, contentPaths }),
	listContentProviders: () => __TAURI_INVOKE<CapabilityEntryDto<ContentProviderCapabilityMetadataDto>[]>("plugin:instance|list_content_providers"),
	searchContent: (payload: ContentSearchParamsDto) => __TAURI_INVOKE<ContentSearchResultDto>("plugin:instance|search_content", { payload }),
	checkCompatibility: (instanceIds: string[], checkParams: ContentCompatibilityCheckParamsDto) => __TAURI_INVOKE<{ [key in string]: ContentCompatibilityResultDto }>("plugin:instance|check_compatibility", { instanceIds, checkParams }),
	getContent: (params: ContentGetParamsDto) => __TAURI_INVOKE<ContentItemDto>("plugin:instance|get_content", { params }),
	listContentVersion: (params: ContentListVersionParamsDto) => __TAURI_INVOKE<ContentVersionDto[]>("plugin:instance|list_content_version", { params }),
};

/** Events */
export const events = {
	instanceEventDto: makeEvent<InstanceEventDto>("plugin:instance:instance-event-dto"),
};

/* Types */
export type AppSettingsErrorDto = { code: "CAN_NOT_SET_EFFECT"; payload: {
	details: string,
} } | { code: "CAN_NOT_RECREATE_WINDOW"; payload: {
	details: string,
} } | { code: "SAVE_FAILED" };

export type AtomicInstallParamsDto = {
	instanceId: string,
	gameVersion: string,
	loader?: string | null,
	contentType: ContentTypeDto,
} & (BaseContentParamsDto);

export type AuthErrorDto = { code: "CREDENTIALS_NOT_FOUND"; payload: {
	id: string,
} } | { code: "NO_ACTIVE_CREDENTIALS" } | { code: "INVALID_USERNAME_LENGTH"; payload: {
	min: number,
	max: number,
} } | { code: "INVALID_USERNAME_CHARS" } | { code: "TOKEN_EXPIRED" } | { code: "STORAGE_ERROR" };

export type BaseContentParamsDto = {
	contentId: string,
	contentVersion?: string | null,
	providerId: ProviderIdDto,
};

export type CapabilityEntryDto<C> = {
	pluginId: string,
	capability: C,
};

export type CapabilityMetadataDto = {
	// Identifier for the capability (lowercase, kebab/underscore allowed).
	id: string,
	// Display name of the capability.
	name: string,
	// Optional detailed description of what this capability does.
	description: string | null,
	// Optional icon file name or URL for the UI.
	icon: string | null,
};

export type ContentCompatibilityCheckParamsDto = {
	providerId: ProviderIdDto,
	contentItem: ContentItemDto,
};

export type ContentCompatibilityResultDto = {
	isCompatible: boolean,
};

export type ContentFileDto = {
	contentPath: string,
	contentType: ContentTypeDto,
	disabled: boolean,
	fileName: string,
	hash: string,
	name: string | null,
	size: number,
	version: string | null,
	updateProviderId: ProviderIdDto | null,
	update?: { [key in string]: ContentFileUpdateInfoDto } | null,
};

export type ContentFileUpdateInfoDto = {
	contentId: string,
	version: string,
};

export type ContentGetParamsDto = {
	contentId: string,
	providerId: ProviderIdDto,
};

export type ContentInstallParamsDto = { type: "atomic"; data: AtomicInstallParamsDto } | { type: "modpack"; data: ModpackInstallParamsDto };

export type ContentItemDto = {
	id: string,
	slug: string,
	name: string,
	description: string | null,
	longDescription: string | null,
	author: string,
	url: string,
	iconUrl: string,
	versions: string[],
	contentType: ContentTypeDto,
};

export type ContentListVersionParamsDto = {
	contentId: string,
	providerId: ProviderIdDto,
};

export type ContentProviderCapabilityMetadataDto = {
	// Whether the provider supports installing individual items (e.g., a single mod or resource pack).
	supportsInstallAtomic: boolean,
	// Whether the provider supports installing complex modpacks or curated collections.
	supportsInstallModpacks: boolean,
} & (CapabilityMetadataDto);

export type ContentSearchParamsDto = {
	contentType: ContentTypeDto,
	providerId: ProviderIdDto,
	page: number,
	pageSize: number,
	query?: string | null,
	gameVersions?: string[] | null,
	loader?: ModLoaderDto | null,
};

export type ContentSearchResultDto = {
	page: number,
	pageSize: number,
	pageCount: number,
	providerId: ProviderIdDto,
	items: ContentItemDto[],
};

export type ContentTypeDto = "modpack" | "mod" | "datapack" | "resourcepack" | "shaderpack";

export type ContentVersionDependencyDto = {
	version_id: string | null,
	content_id: string | null,
	file_name: string | null,
	dependency_type: ContentVersionDependencyTypeDto,
};

export type ContentVersionDependencyTypeDto = "required" | "optional" | "incompatible" | "embedded";

export type ContentVersionDto = {
	id: string,
	contentId: string,
	authorId: string,
	name: string,
	versionNumber: string,
	changelog: string | null,
	dependencies: ContentVersionDependencyDto[],
	gameVersions: string[],
	versionType: ContentVersionTypeDto,
	loaders: ModLoaderDto[],
	featured: boolean,
	status: ContentVersionStatusDto,
	requestedStatus: RequestedContentVersionStatusDto | null,
	datePublished: string,
	downloads: number,
	webUrl: string,
};

export type ContentVersionStatusDto = "listed" | "archived" | "draft" | "unlisted" | "scheduled" | "unknown";

export type ContentVersionTypeDto = "release" | "beta" | "alpha";

export type EditHooksDto = {
	preLaunch?: string | null,
	wrapper?: string | null,
	postExit?: string | null,
};

export type EditInstanceDto = {
	name?: string | null,
	javaPath?: string | null,
	launchArgs?: string[] | null,
	envVars?: ([string, string])[] | null,
	memory?: MemorySettingsDto | null,
	gameResolution?: WindowSizeDto | null,
	hooks?: EditHooksDto | null,
};

export type EventErrorDto = { code: "NOT_INITIALIZED" } | { code: "NO_LOADING_BAR"; payload: {
	id: string,
} } | { code: "SERIALIZE_ERROR"; payload: {
	details: string,
} } | { code: "STORAGE_ERROR"; payload: {
	details: string,
} };

export type FileWatcherErrorDto = { code: "PATH_NOT_FOUND"; payload: {
	path: string,
} } | { code: "WATCH_NOT_FOUND" } | { code: "NOTIFY_ERROR"; payload: {
	details: string,
} };

export type FrontendError = { type: "appSettings"; payload: AppSettingsErrorDto } | { type: "window"; payload: WindowErrorDto } | { type: "auth"; payload: AuthErrorDto } | { type: "event"; payload: EventErrorDto } | { type: "fileWatcher"; payload: FileWatcherErrorDto } | { type: "instance"; payload: InstanceErrorDto } | { type: "java"; payload: JavaErrorDto } | { type: "minecraft"; payload: MinecraftErrorDto } | { type: "plugin"; payload: PluginErrorDto } | { type: "process"; payload: ProcessErrorDto } | { type: "request"; payload: RequestErrorDto } | { type: "settings"; payload: SettingsErrorDto } | 
// General errors that are expected and can be shown to the user.
{ type: "generic"; payload: string } | 
/**
 *  Critical or unexpected errors that indicate a logic failure or
 *  improper error mapping. These should ideally never reach the frontend
 *  but serve as a safety net to prevent silent crashes.
 */
{ type: "internal"; payload: string };

export type HooksDto = {
	preLaunch: string | null,
	wrapper: string | null,
	postExit: string | null,
};

export type ImportInstanceDto = {
	pluginId: string,
	importerId: string,
	path: string,
};

export type ImporterCapabilityMetadataDto = {
	//Optional field label shown in the importer UI.
	fieldLabel: string | null,
	// List of supported file extensions, e.g., [`zip`, `mrpack`].
	supportedExtensions: string[],
} & (CapabilityMetadataDto);

export type InstanceDto = {
	id: string,
	name: string,
	iconPath: string | null,
	installStage: InstanceInstallStageDto,
	gameVersion: string,
	loader: ModLoaderDto,
	loaderVersion: LoaderVersionPreferenceDto | null,
	javaPath: string | null,
	launchArgs: string[] | null,
	envVars: ([string, string])[] | null,
	memory: MemorySettingsDto | null,
	forceFullscreen: boolean | null,
	gameResolution: WindowSizeDto | null,
	created: string,
	modified: string,
	lastPlayed: string | null,
	timePlayed: number,
	recentTimePlayed: number,
	hooks: HooksDto,
	packInfo: PackInfoDto | null,
};

export type InstanceErrorDto = { code: "STORAGE_FAILURE"; payload: {
	details: string,
} } | { code: "CONTENT_PROVIDER_NOT_FOUND"; payload: {
	plugin_id: string,
	capability_id: string,
} } | { code: "CAPABILITY_OPERATION_ERROR" } | { code: "INSTANCE_STILL_INSTALLING"; payload: {
	instance_id: string,
} } | { code: "INSTANCE_ALREADY_RUNNING"; payload: {
	instance_id: string,
	process_id: string,
} } | { code: "PRELAUNCH_COMMAND_ERROR"; payload: {
	code: number,
} } | { code: "VALIDATION_ERROR"; payload: {
	field: string,
	reason: string,
} } | { code: "IMPORTER_NOT_FOUND"; payload: {
	importer_id: string,
} } | { code: "IMPORT_FAILED"; payload: {
	plugin_id: string,
	capability_id: string,
} } | { code: "PACK_INFO_NOT_FOUND" } | { code: "UPDATER_NOT_FOUND"; payload: {
	modpack_id: string,
} } | { code: "UPDATE_FAILED"; payload: {
	modpack_id: string,
} } | { code: "UNMANAGED_INSTANCE"; payload: {
	instance_id: string,
} } | { code: "CONTENT_DUPLICATION"; payload: {
	content_path: string,
} } | { code: "CONTENT_FILENAME"; payload: {
	path: string,
} } | { code: "CONTENT_DOWNLOAD_ERROR"; payload: string } | { code: "CONTENT_PROVIDER_ERROR"; payload: {
	reason: string,
} } | { code: "CONTENT_FOR_GAME_VERSION_NOT_FOUND"; payload: {
	game_version: string,
} } | { code: "UNSUPPORTED_CONTENT_TYPE"; payload: {
	content_type: ContentTypeDto,
} } | { code: "SETTINGS_LOAD_ERROR"; payload: {
	details: string,
} } | { code: "MINECRAFT_ERROR"; payload: {
	details: string,
} } | { code: "PROCESS_ERROR"; payload: {
	details: string,
} } | { code: "CREDENTIALS_ERROR"; payload: {
	details: string,
} };

export type InstanceEventDto = {
	event: InstanceEventTypeDto,
	instanceId: string,
};

export type InstanceEventTypeDto = "created" | "synced" | "edited" | "removed";

export type InstanceInstallStageDto = 
// Instance is installed
"installed" | 
// Instance's minecraft game is still installing
"installing" | 
// Instance created for pack, but the pack hasn't been fully installed yet
"pack_installing" | 
// Instance is not installed
"not_installed";

export type JavaErrorDto = { code: "NOT_FOUND"; payload: {
	version: number,
} } | { code: "INVALID_PATH"; payload: {
	path: string,
} } | { code: "INVALID_VERSION"; payload: {
	version: string,
} } | { code: "FAILED_TO_GET_PROPERTIES"; payload: {
	reason: string,
} } | { code: "VERSION_NOT_AVAILABLE"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "VERSION_GET_FAILED"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "FAILED_TO_INSTALL"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "REMOVE_OLD_INSTALLATION_ERROR"; payload: {
	path: string,
} } | { code: "DOWNLOAD_FAILED"; payload: {
	details: string,
} } | { code: "STORAGE_ERROR"; payload: {
	details: string,
} };

export type LoadConfigDto = 
// Use WebAssembly (Extism) for a secure, cross-platform sandbox.
{ type: "extism"; 
// Path to the .wasm file relative to the plugin root.
file: string; 
// Maximum memory (in bytes) the plugin is allowed to allocate.
memoryLimit?: number | null } | 
// Load a native shared library (.dll, .so, .dylib). Less secure, but faster.
{ type: "native"; 
// Path to the dynamic library file relative to the plugin root.
libPath: string };

export type LoadConfigTypeDto = "extism" | "native";

export type LoaderVersionPreferenceDto = "latest" | "stable" | string;

export type MemorySettingsDto = {
	maximum: number,
};

export type MinecraftErrorDto = { code: "VERSION_NOT_FOUND"; payload: {
	version: string,
} } | { code: "VERSION_FOR_LOADER_NOT_FOUND"; payload: {
	loader_version_preference: LoaderVersionPreferenceDto,
} } | { code: "LOADER_NOT_FOUND"; payload: {
	loader_version_preference: LoaderVersionPreferenceDto,
} } | { code: "LOADER_VERSION_REQUIRED" } | { code: "DEFAULT_LOADER_NOT_FOUND" } | { code: "PROCESSOR_FAILED"; payload: {
	reason: string,
} } | { code: "PRE_LAUNCH_FAILED"; payload: {
	code: number,
} } | { code: "POST_LAUNCH_FAILED"; payload: {
	code: number,
} } | { code: "PATH_NOT_FOUND"; payload: {
	path: string,
	entity_type: string,
} } | { code: "PARSE_FAILED"; payload: {
	reason: string,
} } | { code: "STORAGE_FAILURE"; payload: {
	reason: string,
} } | { code: "JAVA_ERROR"; payload: {
	details: string,
} } | { code: "STORAGE"; payload: {
	details: string,
} };

export type MinecraftProcessMetadataDto = {
	uuid: string,
	instance_id: string,
	start_time: string,
};

export type ModLoaderDto = "vanilla" | "forge" | "fabric" | "quilt" | "neoforge";

export type ModpackInstallParamsDto = (BaseContentParamsDto);

export type NewInstanceDto = {
	name: string,
	gameVersion: string,
	modLoader: ModLoaderDto,
	loaderVersion?: LoaderVersionPreferenceDto | null,
	iconPath?: string | null,
	skipInstallInstance?: boolean | null,
	packInfo?: PackInfoDto | null,
};

export type PackInfoDto = {
	pluginId: string,
	modpackId: string,
	version: string,
};

export type PluginErrorDto = { code: "NOT_FOUND"; payload: {
	plugin_id: string,
} } | { code: "ALREADY_LOADED"; payload: {
	plugin_id: string,
} } | { code: "LOADING_IN_PROGRESS"; payload: {
	plugin_id: string,
} } | { code: "UNLOADING_IN_PROGRESS"; payload: {
	plugin_id: string,
} } | { code: "ALREADY_UNLOADED"; payload: {
	plugin_id: string,
} } | { code: "LOAD_FAILED"; payload: {
	plugin_id: string,
	reason: string,
} } | { code: "FUNCTION_CALL_FAILED"; payload: {
	function_name: string,
	plugin_id: string,
	error: string,
} } | { code: "MANIFEST_NOT_FOUND"; payload: {
	path: string,
} } | { code: "INVALID_MANIFEST_FORMAT"; payload: {
	error: string,
} } | { code: "LOADER_NOT_FOUND"; payload: {
	config_type: LoadConfigTypeDto,
} } | { code: "INVALID_CONFIG"; payload: {
	config: LoadConfigDto,
} } | { code: "EXTRACTION_FAILED"; payload: {
	from: string,
} } | { code: "INVALID_EXTRACTION_FORMAT" } | { code: "FILE_EXTRACTION_FAILED"; payload: {
	from: string,
} } | { code: "CAPABILITY_REGISTRATION_FAILED"; payload: {
	capability_type: string,
	capability_id: string,
} } | { code: "CAPABILITY_CANCEL_REGISTRATION_FAILED"; payload: {
	capability_type: string,
	capability_id: string,
} } | { code: "ACCESS_VIOLATION"; payload: {
	plugin_id: string,
	path: string,
} } | { code: "HASH_COMPUTATION_FAILED" } | { code: "SETTINGS"; payload: {
	details: string,
} } | { code: "STORAGE"; payload: {
	details: string,
} };

export type ProcessErrorDto = { code: "KILL_ERROR"; payload: {
	id: string,
} } | { code: "WAIT_ERROR"; payload: {
	id: string,
} } | { code: "IO"; payload: {
	details: string,
} };

export type ProviderIdDto = {
	pluginId: string,
	capabilityId: string,
};

export type RequestErrorDto = { code: "ACQUIRE_ERROR" } | { code: "REQUEST_SEND_ERROR"; payload: {
	details: string,
} } | { code: "MIDDLEWARE_ERROR"; payload: {
	details: string,
} } | { code: "HASH_ERROR"; payload: {
	actual: string,
	expected: string,
} } | { code: "JSON_ERROR"; payload: {
	details: string,
} } | { code: "TOML_ERROR"; payload: {
	details: string,
} } | { code: "PARSE_ERROR" };

export type RequestedContentVersionStatusDto = "listed" | "archived" | "draft" | "unlisted";

export type SettingsErrorDto = { code: "NOT_FOUND" } | { code: "STORAGE_FAILURE" };

export type WindowErrorDto = { code: "ALREADY_EXISTS"; payload: {
	label: WindowLabelDto,
} } | { code: "NOT_FOUND"; payload: {
	label: WindowLabelDto,
} } | { code: "PLATFORM_NOT_SUPPORTED"; payload: {
	details: string,
} } | { code: "OTHER"; payload: {
	details: string,
} };

export type WindowLabelDto = "main";

export type WindowSizeDto = [number, number];

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

