// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	import: (paths: string[]) => __TAURI_INVOKE<null>("plugin:plugin|import", { paths }),
	sync: () => __TAURI_INVOKE<null>("plugin:plugin|sync"),
	list: () => __TAURI_INVOKE<PluginDto[]>("plugin:plugin|list"),
	get: (id: string) => __TAURI_INVOKE<PluginDto>("plugin:plugin|get", { id }),
	remove: (id: string) => __TAURI_INVOKE<null>("plugin:plugin|remove", { id }),
	enable: (id: string) => __TAURI_INVOKE<null>("plugin:plugin|enable", { id }),
	disable: (id: string) => __TAURI_INVOKE<null>("plugin:plugin|disable", { id }),
	call: (id: string, data: string) => __TAURI_INVOKE<null>("plugin:plugin|call", { id, data }),
	getSettings: (id: string) => __TAURI_INVOKE<{
	allowedHosts?: string[],
	allowedPaths?: PathMappingDto[],
} | null>("plugin:plugin|get_settings", { id }),
	editSettings: (id: string, editSettings: EditPluginSettingsDto) => __TAURI_INVOKE<null>("plugin:plugin|edit_settings", { id, editSettings }),
	openPluginsFolder: () => __TAURI_INVOKE<null>("plugin:plugin|open_plugins_folder"),
	getApiVersion: () => __TAURI_INVOKE<string>("plugin:plugin|get_api_version"),
};

/** Events */
export const events = {
	pluginEventDto: makeEvent<PluginEventDto>("plugin:plugin:plugin-event-dto"),
};

/* Types */
export type ApiConfigDto = {
	// Required API version range (`SemVer` requirement).
	version: string,
	// List of optional host features requested by the plugin.
	features?: string[],
};

export type AppSettingsErrorDto = { code: "TRANSPARENT_EFFECT_REQUIRED" } | { code: "CAN_NOT_SET_EFFECT"; payload: {
	details: string,
} } | { code: "SAVE_FAILED" };

export type AuthErrorDto = { code: "CREDENTIALS_NOT_FOUND"; payload: {
	id: string,
} } | { code: "NO_ACTIVE_CREDENTIALS" } | { code: "INVALID_USERNAME_LENGTH"; payload: {
	min: number,
	max: number,
} } | { code: "INVALID_USERNAME_CHARS" } | { code: "TOKEN_EXPIRED" } | { code: "STORAGE_ERROR" };

export type CapabilityMetadataDto = {
	// Identifier for the capability (lowercase, kebab/underscore allowed).
	id: string,
	// Display name of the capability.
	name: string,
	// Optional detailed description of what this capability does.
	description: string | null,
	// Optional icon file name or URL for the UI.
	icon: string | null,
};

export type ContentProviderCapabilityMetadataDto = {
	// Whether the provider supports installing individual items (e.g., a single mod or resource pack).
	supportsInstallAtomic: boolean,
	// Whether the provider supports installing complex modpacks or curated collections.
	supportsInstallModpacks: boolean,
} & (CapabilityMetadataDto);

export type ContentTypeDto = "modpack" | "mod" | "datapack" | "resourcepack" | "shaderpack";

export type EditPluginSettingsDto = {
	allowedHosts?: string[] | null,
	allowedPaths?: PathMappingDto[] | null,
};

export type EventErrorDto = { code: "NOT_INITIALIZED" } | { code: "NO_LOADING_BAR"; payload: {
	id: string,
} } | { code: "SERIALIZE_ERROR"; payload: {
	details: string,
} } | { code: "STORAGE_ERROR"; payload: {
	details: string,
} };

export type FileWatcherErrorDto = { code: "PATH_NOT_FOUND"; payload: {
	path: string,
} } | { code: "WATCH_NOT_FOUND" } | { code: "NOTIFY_ERROR"; payload: {
	details: string,
} };

export type FrontendError = { type: "appSettings"; payload: AppSettingsErrorDto } | { type: "auth"; payload: AuthErrorDto } | { type: "event"; payload: EventErrorDto } | { type: "fileWatcher"; payload: FileWatcherErrorDto } | { type: "instance"; payload: InstanceErrorDto } | { type: "java"; payload: JavaErrorDto } | { type: "minecraft"; payload: MinecraftErrorDto } | { type: "plugin"; payload: PluginErrorDto } | { type: "process"; payload: ProcessErrorDto } | { type: "request"; payload: RequestErrorDto } | { type: "settings"; payload: SettingsErrorDto } | 
// General errors that are expected and can be shown to the user.
{ type: "generic"; payload: string } | 
/**
 *  Critical or unexpected errors that indicate a logic failure or
 *  improper error mapping. These should ideally never reach the frontend
 *  but serve as a safety net to prevent silent crashes.
 */
{ type: "internal"; payload: string };

export type ImporterCapabilityMetadataDto = {
	//Optional field label shown in the importer UI.
	fieldLabel: string | null,
	// List of supported file extensions, e.g., [`zip`, `mrpack`].
	supportedExtensions: string[],
} & (CapabilityMetadataDto);

export type InstanceErrorDto = { code: "STORAGE_FAILURE"; payload: {
	details: string,
} } | { code: "CONTENT_PROVIDER_NOT_FOUND"; payload: {
	plugin_id: string,
	capability_id: string,
} } | { code: "CAPABILITY_OPERATION_ERROR" } | { code: "INSTANCE_STILL_INSTALLING"; payload: {
	instance_id: string,
} } | { code: "INSTANCE_ALREADY_RUNNING"; payload: {
	instance_id: string,
	process_id: string,
} } | { code: "PRELAUNCH_COMMAND_ERROR"; payload: {
	code: number,
} } | { code: "VALIDATION_ERROR"; payload: {
	field: string,
	reason: string,
} } | { code: "IMPORTER_NOT_FOUND"; payload: {
	importer_id: string,
} } | { code: "IMPORT_FAILED"; payload: {
	plugin_id: string,
	capability_id: string,
} } | { code: "PACK_INFO_NOT_FOUND" } | { code: "UPDATER_NOT_FOUND"; payload: {
	modpack_id: string,
} } | { code: "UPDATE_FAILED"; payload: {
	modpack_id: string,
} } | { code: "UNMANAGED_INSTANCE"; payload: {
	instance_id: string,
} } | { code: "CONTENT_DUPLICATION"; payload: {
	content_path: string,
} } | { code: "CONTENT_FILENAME"; payload: {
	path: string,
} } | { code: "CONTENT_DOWNLOAD_ERROR"; payload: string } | { code: "CONTENT_PROVIDER_ERROR"; payload: {
	reason: string,
} } | { code: "CONTENT_FOR_GAME_VERSION_NOT_FOUND"; payload: {
	game_version: string,
} } | { code: "UNSUPPORTED_CONTENT_TYPE"; payload: {
	content_type: ContentTypeDto,
} } | { code: "SETTINGS_LOAD_ERROR"; payload: {
	details: string,
} } | { code: "MINECRAFT_ERROR"; payload: {
	details: string,
} } | { code: "PROCESS_ERROR"; payload: {
	details: string,
} } | { code: "CREDENTIALS_ERROR"; payload: {
	details: string,
} };

export type JavaErrorDto = { code: "NOT_FOUND"; payload: {
	version: number,
} } | { code: "INVALID_PATH"; payload: {
	path: string,
} } | { code: "INVALID_VERSION"; payload: {
	version: string,
} } | { code: "FAILED_TO_GET_PROPERTIES"; payload: {
	reason: string,
} } | { code: "VERSION_NOT_AVAILABLE"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "VERSION_GET_FAILED"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "FAILED_TO_INSTALL"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "REMOVE_OLD_INSTALLATION_ERROR"; payload: {
	path: string,
} } | { code: "DOWNLOAD_FAILED"; payload: {
	details: string,
} } | { code: "STORAGE_ERROR"; payload: {
	details: string,
} };

export type LoadConfigDto = 
// Use WebAssembly (Extism) for a secure, cross-platform sandbox.
{ type: "extism"; 
// Path to the .wasm file relative to the plugin root.
file: string; 
// Maximum memory (in bytes) the plugin is allowed to allocate.
memoryLimit?: number | null } | 
// Load a native shared library (.dll, .so, .dylib). Less secure, but faster.
{ type: "native"; 
// Path to the dynamic library file relative to the plugin root.
libPath: string };

export type LoadConfigTypeDto = "extism" | "native";

export type LoaderVersionPreferenceDto = "latest" | "stable" | string;

export type MinecraftErrorDto = { code: "VERSION_NOT_FOUND"; payload: {
	version: string,
} } | { code: "VERSION_FOR_LOADER_NOT_FOUND"; payload: {
	loader_version_preference: LoaderVersionPreferenceDto,
} } | { code: "LOADER_NOT_FOUND"; payload: {
	loader_version_preference: LoaderVersionPreferenceDto,
} } | { code: "LOADER_VERSION_REQUIRED" } | { code: "DEFAULT_LOADER_NOT_FOUND" } | { code: "PROCESSOR_FAILED"; payload: {
	reason: string,
} } | { code: "PRE_LAUNCH_FAILED"; payload: {
	code: number,
} } | { code: "POST_LAUNCH_FAILED"; payload: {
	code: number,
} } | { code: "PATH_NOT_FOUND"; payload: {
	path: string,
	entity_type: string,
} } | { code: "PARSE_FAILED"; payload: {
	reason: string,
} } | { code: "STORAGE_FAILURE"; payload: {
	reason: string,
} } | { code: "JAVA_ERROR"; payload: {
	details: string,
} } | { code: "STORAGE"; payload: {
	details: string,
} };

/**
 *  A mapping between a path on the host and a virtual path in the plugin.
 *  Format: [`host_path`, `virtual_path`]
 */
export type PathMappingDto = [
// Path on the host disk.
string, 
// Virtual path inside the plugin sandbox.
string];

// Describes the declarative capabilities of a plugin, such as supported importers.
export type PluginCapabilitiesDto = {
	// List of supported modpack importers provided by the plugin.
	importers?: PluginImporterCapabilityDto[],
	// List of supported modpack updaters provided by the plugin.
	updaters?: PluginUpdaterCapabilityDto[],
	// List of content providers provided by the plugin.
	contentProviders?: PluginContentProviderCapabilityDto[],
};

export type PluginContentProviderCapabilityDto = {
	// Set of functions provided by the plugin to handle content operations.
	handlers: ProviderHandlersDto,
} & (ContentProviderCapabilityMetadataDto);

export type PluginDto = {
	manifest: PluginManifestDto,
	capabilities: PluginCapabilitiesDto | null,
	state: PluginDtoState,
};

export type PluginDtoState = "NotLoaded" | "Loading" | "Loaded" | "Unloading" | "Failed";

export type PluginErrorDto = { code: "NOT_FOUND"; payload: {
	plugin_id: string,
} } | { code: "ALREADY_LOADED"; payload: {
	plugin_id: string,
} } | { code: "LOADING_IN_PROGRESS"; payload: {
	plugin_id: string,
} } | { code: "UNLOADING_IN_PROGRESS"; payload: {
	plugin_id: string,
} } | { code: "ALREADY_UNLOADED"; payload: {
	plugin_id: string,
} } | { code: "LOAD_FAILED"; payload: {
	plugin_id: string,
	reason: string,
} } | { code: "FUNCTION_CALL_FAILED"; payload: {
	function_name: string,
	plugin_id: string,
	error: string,
} } | { code: "MANIFEST_NOT_FOUND"; payload: {
	path: string,
} } | { code: "INVALID_MANIFEST_FORMAT"; payload: {
	error: string,
} } | { code: "LOADER_NOT_FOUND"; payload: {
	config_type: LoadConfigTypeDto,
} } | { code: "INVALID_CONFIG"; payload: {
	config: LoadConfigDto,
} } | { code: "EXTRACTION_FAILED"; payload: {
	from: string,
} } | { code: "INVALID_EXTRACTION_FORMAT" } | { code: "FILE_EXTRACTION_FAILED"; payload: {
	from: string,
} } | { code: "CAPABILITY_REGISTRATION_FAILED"; payload: {
	capability_type: string,
	capability_id: string,
} } | { code: "CAPABILITY_CANCEL_REGISTRATION_FAILED"; payload: {
	capability_type: string,
	capability_id: string,
} } | { code: "ACCESS_VIOLATION"; payload: {
	plugin_id: string,
	path: string,
} } | { code: "HASH_COMPUTATION_FAILED" } | { code: "SETTINGS"; payload: {
	details: string,
} } | { code: "STORAGE"; payload: {
	details: string,
} };

export type PluginEventDto = { type: "add"; plugin_id: string } | { type: "edit"; plugin_id: string } | { type: "remove"; plugin_id: string } | { type: "sync" };

export type PluginImporterCapabilityDto = {
	// Plugin function name to handle this capability call.
	handler: string,
} & (ImporterCapabilityMetadataDto);

// Root configuration for an Aether plugin.
export type PluginManifestDto = {
	// Information about the plugin identity.
	metadata: PluginMetadataDto,
	// Sandbox and security restrictions for the plugin.
	runtime: RuntimeConfigDto,
	// Defines how the plugin code should be loaded and executed.
	load: LoadConfigDto,
	// Integration with the host application API.
	api: ApiConfigDto,
};

export type PluginMetadataDto = {
	// Unique identifier for the plugin (lowercase, kebab-case).
	id: string,
	// Readable name of the plugin.
	name: string,
	// Semantic version of the plugin.
	version: string,
	// Short summary of the plugin's purpose.
	description: string | null,
	// List of plugin authors.
	authors?: string[],
	// License under which the plugin is distributed.
	license: string | null,
};

export type PluginSettingsDto = {
	allowedHosts?: string[],
	allowedPaths?: PathMappingDto[],
};

export type PluginUpdaterCapabilityDto = {
	// Plugin function name to handle this capability call.
	handler: string,
} & (UpdaterCapabilityMetadataDto);

export type ProcessErrorDto = { code: "KILL_ERROR"; payload: {
	id: string,
} } | { code: "WAIT_ERROR"; payload: {
	id: string,
} } | { code: "IO"; payload: {
	details: string,
} };

// Names of plugin functions that implement specific content provider logic.
export type ProviderHandlersDto = {
	// Function to search for content within the provider.
	search: string,
	// Function to get detailed information about a specific piece of content.
	getContent: string,
	// Optional function to list available versions of a specific content item.
	listVersion: string | null,
	// Function to handle the download and installation of a single item.
	installAtomic: string,
	// Optional function to handle the installation of full modpacks.
	installModpack: string | null,
	// Optional function to check if a specific content item is compatible with current environment.
	checkCompatibility: string | null,
};

export type RequestErrorDto = { code: "ACQUIRE_ERROR" } | { code: "REQUEST_SEND_ERROR"; payload: {
	details: string,
} } | { code: "MIDDLEWARE_ERROR"; payload: {
	details: string,
} } | { code: "HASH_ERROR"; payload: {
	actual: string,
	expected: string,
} } | { code: "JSON_ERROR"; payload: {
	details: string,
} } | { code: "TOML_ERROR"; payload: {
	details: string,
} } | { code: "PARSE_ERROR" };

export type RuntimeConfigDto = {
	// List of domains or IP addresses the plugin is allowed to connect to.
	allowedHosts?: string[],
	// Filesystem access restrictions. Maps host paths to plugin-internal paths.
	allowedPaths?: PathMappingDto[],
};

export type SettingsErrorDto = { code: "NOT_FOUND" } | { code: "STORAGE_FAILURE" };

export type UpdaterCapabilityMetadataDto = (CapabilityMetadataDto);

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

