// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	get: () => __TAURI_INVOKE<SettingsDto>("plugin:settings|get"),
	edit: (editSettings: EditSettingsDto) => __TAURI_INVOKE<SettingsDto>("plugin:settings|edit", { editSettings }),
	getMaxRam: () => __TAURI_INVOKE<number>("plugin:settings|get_max_ram"),
	getDefaultInstanceSettings: () => __TAURI_INVOKE<DefaultInstanceSettingsDto>("plugin:settings|get_default_instance_settings"),
	editDefaultInstanceSettings: (editSettings: EditDefaultInstanceSettingsDto) => __TAURI_INVOKE<DefaultInstanceSettingsDto>("plugin:settings|edit_default_instance_settings", { editSettings }),
	getAppSettings: () => __TAURI_INVOKE<AppSettingsDto>("plugin:settings|get_app_settings"),
	editAppSettings: (editAppSettings: EditAppSettingsDto) => __TAURI_INVOKE<AppSettingsDto>("plugin:settings|edit_app_settings", { editAppSettings }),
	recreateWindow: () => __TAURI_INVOKE<null>("plugin:settings|recreate_window"),
};

/* Types */
export type ActionOnInstanceLaunchDto = "nothing" | "hide" | "close";

export type AppSettingsDto = {
	actionOnInstanceLaunch: ActionOnInstanceLaunchDto,
	isActualTransparent: boolean,
	transparent: boolean,
	windowEffect: WindowEffectDto,
};

export type AppSettingsErrorDto = { code: "TRANSPARENT_EFFECT_REQUIRED" } | { code: "CAN_NOT_SET_EFFECT"; payload: {
	details: string,
} } | { code: "CAN_NOT_RECREATE_WINDOW"; payload: {
	details: string,
} } | { code: "SAVE_FAILED" };

export type AuthErrorDto = { code: "CREDENTIALS_NOT_FOUND"; payload: {
	id: string,
} } | { code: "NO_ACTIVE_CREDENTIALS" } | { code: "INVALID_USERNAME_LENGTH"; payload: {
	min: number,
	max: number,
} } | { code: "INVALID_USERNAME_CHARS" } | { code: "TOKEN_EXPIRED" } | { code: "STORAGE_ERROR" };

export type ContentTypeDto = "modpack" | "mod" | "datapack" | "resourcepack" | "shaderpack";

export type DefaultInstanceSettingsDto = {
	launchArgs: string[],
	envVars: ([string, string])[],
	memory: MemorySettingsDto,
	gameResolution: WindowSizeDto,
	hooks: HooksDto,
};

export type EditAppSettingsDto = {
	actionOnInstanceLaunch?: ActionOnInstanceLaunchDto | null,
	transparent?: boolean | null,
	windowEffect?: WindowEffectDto | null,
};

export type EditDefaultInstanceSettingsDto = {
	launchArgs?: string[] | null,
	envVars?: ([string, string])[] | null,
	memory?: MemorySettingsDto | null,
	gameResolution?: WindowSizeDto | null,
	hooks?: EditHooksDto | null,
};

export type EditHooksDto = {
	preLaunch?: string | null,
	wrapper?: string | null,
	postExit?: string | null,
};

export type EditSettingsDto = {
	maxConcurrentDownloads: number,
};

export type EventErrorDto = { code: "NOT_INITIALIZED" } | { code: "NO_LOADING_BAR"; payload: {
	id: string,
} } | { code: "SERIALIZE_ERROR"; payload: {
	details: string,
} } | { code: "STORAGE_ERROR"; payload: {
	details: string,
} };

export type FileWatcherErrorDto = { code: "PATH_NOT_FOUND"; payload: {
	path: string,
} } | { code: "WATCH_NOT_FOUND" } | { code: "NOTIFY_ERROR"; payload: {
	details: string,
} };

export type FrontendError = { type: "appSettings"; payload: AppSettingsErrorDto } | { type: "auth"; payload: AuthErrorDto } | { type: "event"; payload: EventErrorDto } | { type: "fileWatcher"; payload: FileWatcherErrorDto } | { type: "instance"; payload: InstanceErrorDto } | { type: "java"; payload: JavaErrorDto } | { type: "minecraft"; payload: MinecraftErrorDto } | { type: "plugin"; payload: PluginErrorDto } | { type: "process"; payload: ProcessErrorDto } | { type: "request"; payload: RequestErrorDto } | { type: "settings"; payload: SettingsErrorDto } | 
// General errors that are expected and can be shown to the user.
{ type: "generic"; payload: string } | 
/**
 *  Critical or unexpected errors that indicate a logic failure or
 *  improper error mapping. These should ideally never reach the frontend
 *  but serve as a safety net to prevent silent crashes.
 */
{ type: "internal"; payload: string };

export type HooksDto = {
	preLaunch: string | null,
	wrapper: string | null,
	postExit: string | null,
};

export type InstanceErrorDto = { code: "STORAGE_FAILURE"; payload: {
	details: string,
} } | { code: "CONTENT_PROVIDER_NOT_FOUND"; payload: {
	plugin_id: string,
	capability_id: string,
} } | { code: "CAPABILITY_OPERATION_ERROR" } | { code: "INSTANCE_STILL_INSTALLING"; payload: {
	instance_id: string,
} } | { code: "INSTANCE_ALREADY_RUNNING"; payload: {
	instance_id: string,
	process_id: string,
} } | { code: "PRELAUNCH_COMMAND_ERROR"; payload: {
	code: number,
} } | { code: "VALIDATION_ERROR"; payload: {
	field: string,
	reason: string,
} } | { code: "IMPORTER_NOT_FOUND"; payload: {
	importer_id: string,
} } | { code: "IMPORT_FAILED"; payload: {
	plugin_id: string,
	capability_id: string,
} } | { code: "PACK_INFO_NOT_FOUND" } | { code: "UPDATER_NOT_FOUND"; payload: {
	modpack_id: string,
} } | { code: "UPDATE_FAILED"; payload: {
	modpack_id: string,
} } | { code: "UNMANAGED_INSTANCE"; payload: {
	instance_id: string,
} } | { code: "CONTENT_DUPLICATION"; payload: {
	content_path: string,
} } | { code: "CONTENT_FILENAME"; payload: {
	path: string,
} } | { code: "CONTENT_DOWNLOAD_ERROR"; payload: string } | { code: "CONTENT_PROVIDER_ERROR"; payload: {
	reason: string,
} } | { code: "CONTENT_FOR_GAME_VERSION_NOT_FOUND"; payload: {
	game_version: string,
} } | { code: "UNSUPPORTED_CONTENT_TYPE"; payload: {
	content_type: ContentTypeDto,
} } | { code: "SETTINGS_LOAD_ERROR"; payload: {
	details: string,
} } | { code: "MINECRAFT_ERROR"; payload: {
	details: string,
} } | { code: "PROCESS_ERROR"; payload: {
	details: string,
} } | { code: "CREDENTIALS_ERROR"; payload: {
	details: string,
} };

export type JavaErrorDto = { code: "NOT_FOUND"; payload: {
	version: number,
} } | { code: "INVALID_PATH"; payload: {
	path: string,
} } | { code: "INVALID_VERSION"; payload: {
	version: string,
} } | { code: "FAILED_TO_GET_PROPERTIES"; payload: {
	reason: string,
} } | { code: "VERSION_NOT_AVAILABLE"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "VERSION_GET_FAILED"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "FAILED_TO_INSTALL"; payload: {
	version: number,
	os: string,
	arch: string,
} } | { code: "REMOVE_OLD_INSTALLATION_ERROR"; payload: {
	path: string,
} } | { code: "DOWNLOAD_FAILED"; payload: {
	details: string,
} } | { code: "STORAGE_ERROR"; payload: {
	details: string,
} };

export type LoadConfigDto = 
// Use WebAssembly (Extism) for a secure, cross-platform sandbox.
{ type: "extism"; 
// Path to the .wasm file relative to the plugin root.
file: string; 
// Maximum memory (in bytes) the plugin is allowed to allocate.
memoryLimit?: number | null } | 
// Load a native shared library (.dll, .so, .dylib). Less secure, but faster.
{ type: "native"; 
// Path to the dynamic library file relative to the plugin root.
libPath: string };

export type LoadConfigTypeDto = "extism" | "native";

export type LoaderVersionPreferenceDto = "latest" | "stable" | string;

export type MemorySettingsDto = {
	maximum: number,
};

export type MinecraftErrorDto = { code: "VERSION_NOT_FOUND"; payload: {
	version: string,
} } | { code: "VERSION_FOR_LOADER_NOT_FOUND"; payload: {
	loader_version_preference: LoaderVersionPreferenceDto,
} } | { code: "LOADER_NOT_FOUND"; payload: {
	loader_version_preference: LoaderVersionPreferenceDto,
} } | { code: "LOADER_VERSION_REQUIRED" } | { code: "DEFAULT_LOADER_NOT_FOUND" } | { code: "PROCESSOR_FAILED"; payload: {
	reason: string,
} } | { code: "PRE_LAUNCH_FAILED"; payload: {
	code: number,
} } | { code: "POST_LAUNCH_FAILED"; payload: {
	code: number,
} } | { code: "PATH_NOT_FOUND"; payload: {
	path: string,
	entity_type: string,
} } | { code: "PARSE_FAILED"; payload: {
	reason: string,
} } | { code: "STORAGE_FAILURE"; payload: {
	reason: string,
} } | { code: "JAVA_ERROR"; payload: {
	details: string,
} } | { code: "STORAGE"; payload: {
	details: string,
} };

export type PluginErrorDto = { code: "NOT_FOUND"; payload: {
	plugin_id: string,
} } | { code: "ALREADY_LOADED"; payload: {
	plugin_id: string,
} } | { code: "LOADING_IN_PROGRESS"; payload: {
	plugin_id: string,
} } | { code: "UNLOADING_IN_PROGRESS"; payload: {
	plugin_id: string,
} } | { code: "ALREADY_UNLOADED"; payload: {
	plugin_id: string,
} } | { code: "LOAD_FAILED"; payload: {
	plugin_id: string,
	reason: string,
} } | { code: "FUNCTION_CALL_FAILED"; payload: {
	function_name: string,
	plugin_id: string,
	error: string,
} } | { code: "MANIFEST_NOT_FOUND"; payload: {
	path: string,
} } | { code: "INVALID_MANIFEST_FORMAT"; payload: {
	error: string,
} } | { code: "LOADER_NOT_FOUND"; payload: {
	config_type: LoadConfigTypeDto,
} } | { code: "INVALID_CONFIG"; payload: {
	config: LoadConfigDto,
} } | { code: "EXTRACTION_FAILED"; payload: {
	from: string,
} } | { code: "INVALID_EXTRACTION_FORMAT" } | { code: "FILE_EXTRACTION_FAILED"; payload: {
	from: string,
} } | { code: "CAPABILITY_REGISTRATION_FAILED"; payload: {
	capability_type: string,
	capability_id: string,
} } | { code: "CAPABILITY_CANCEL_REGISTRATION_FAILED"; payload: {
	capability_type: string,
	capability_id: string,
} } | { code: "ACCESS_VIOLATION"; payload: {
	plugin_id: string,
	path: string,
} } | { code: "HASH_COMPUTATION_FAILED" } | { code: "SETTINGS"; payload: {
	details: string,
} } | { code: "STORAGE"; payload: {
	details: string,
} };

export type ProcessErrorDto = { code: "KILL_ERROR"; payload: {
	id: string,
} } | { code: "WAIT_ERROR"; payload: {
	id: string,
} } | { code: "IO"; payload: {
	details: string,
} };

export type RequestErrorDto = { code: "ACQUIRE_ERROR" } | { code: "REQUEST_SEND_ERROR"; payload: {
	details: string,
} } | { code: "MIDDLEWARE_ERROR"; payload: {
	details: string,
} } | { code: "HASH_ERROR"; payload: {
	actual: string,
	expected: string,
} } | { code: "JSON_ERROR"; payload: {
	details: string,
} } | { code: "TOML_ERROR"; payload: {
	details: string,
} } | { code: "PARSE_ERROR" };

export type SettingsDto = {
	maxConcurrentDownloads: number,
};

export type SettingsErrorDto = { code: "NOT_FOUND" } | { code: "STORAGE_FAILURE" };

export type WindowEffectDto = "off" | "mica_light" | "mica_dark" | "mica" | "acrylic";

export type WindowSizeDto = [number, number];

