// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	checkForUpdates: () => __TAURI_INVOKE<{
	version: string | null,
	date: string | null,
	body: string | null,
} | null>("plugin:update|check_for_updates"),
	installUpdate: () => __TAURI_INVOKE<null>("plugin:update|install_update"),
};

/* Types */
export type UpdateStatusDto = {
	version: string | null,
	date: string | null,
	body: string | null,
};

