[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = ["-C", "link-args=/STACK:16777216", "-C", "link-arg=-fuse-ld=lld"]

[alias]
bindgen = "run --bin generate-bindings --release --features generate-bindings"

[env]
BINDINGS_EXPORT_PATH = { value = "apps/frontend/src/shared/api/bindings", relative = true }
